CREATE TABLE IF NOT EXISTS rfq_submissions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(300) NOT NULL,
  company VARCHAR(300) NOT NULL,
  email VARCHAR(300) NOT NULL,
  phone VARCHAR(80) NOT NULL,
  product VARCHAR(80) NOT NULL DEFAULT '',
  quote_items TEXT NULL,
  message TEXT NOT NULL,
  attachment_path VARCHAR(255) NULL,
  mail_sent TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS catalog_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_slug VARCHAR(80) NOT NULL,
  item_id VARCHAR(80) NOT NULL,
  name VARCHAR(200) NOT NULL,
  image VARCHAR(255) NOT NULL DEFAULT '',
  packs JSON NOT NULL,
  description TEXT NOT NULL,
  applications TEXT NOT NULL,
  specifications JSON NOT NULL,
  summary VARCHAR(400) NOT NULL DEFAULT '',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY category_item (category_slug, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
